### ISSUE TITLE
Does not run on macOS (Darwin) due to watchbird

### ISSUE THREAD

**Issue by egrieco** [crystallabs/fluence#54]
On macOS running make results in the following error:

``` crystal
Building fluence in /Users/egrieco/Repos/fluence/bin/fluence
Error in src/fluence.cr:1: while requiring "../config/application"

require "../config/application"
^

in config/application.cr:8: while requiring "watchbird/dsl"

require "watchbird/dsl"
^

in lib/watchbird/src/dsl.cr:1: while requiring "./watchbird/watcher"

require "./watchbird/watcher"
^

in lib/watchbird/src/watchbird/watcher.cr:2: not implemented yet in darwin

require "./notifier"
^
```

The [watchbird](https://github.com/Sauilitired/watchbird) shard [does not support macOS, aka darwin](https://github.com/Sauilitired/watchbird/blob/master/src/watchbird/notifier.cr). Any way to disable the watcher functionality?

**Comment by egrieco** [comment]
This can be fixed by commenting out or deleting [fluence/application.cr line 8](https://github.com/crystallabs/fluence/blob/master/config/application.cr#L8).

Since the only place watchbird is "used" is [src/lib/fluence/_init.cr line 73](https://github.com/crystallabs/fluence/blob/master/src/fluence/lib/_init.cr#L73), and that is commented out, this change is recommended.

**Comment by docelic** [comment]
Hey @egrieco, indeed, `watchbird` can be removed because we don't intend to use it anyway.

Originally we wanted to use it to detect changes to wiki files that happen outside of Fluence's web interface (e.g. through direct filesystem access), but later we have decided to simply check page/media file freshness at the time when someone visits it through Fluence.

Also, Fluence currently builds an "index" of the pages on disk, but we are playing with the idea to remove that and simply use the filesystem directly for everything. If we do that, then `watchbird` would be completely unnecessary.

I will make a commit which removes watchbird in the next hour. Thanks for the report!
